name: testjones
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0892459168098867
  lightness: 0.7458908983971924
  saturation: 0.49243959970772266
  rhythmicContrast: 0.4113413526210934
purpose: []
